create table if not exists public.preparation_progress (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    company_name text not null,
    target_role text not null,
    question_text text not null,
    question_type text not null,
    difficulty text not null default 'mid' check (difficulty in ('low', 'mid', 'high')),
    status text not null default 'prepared' check (status in ('prepared', 'practiced')),
    updated_at timestamptz not null default now(),
    unique (user_id, company_name, target_role, question_text)
);

alter table public.preparation_progress enable row level security;

drop policy if exists "Users read own preparation" on public.preparation_progress;
create policy "Users read own preparation"
on public.preparation_progress for select
using (auth.uid() = user_id);

drop policy if exists "Users insert own preparation" on public.preparation_progress;
create policy "Users insert own preparation"
on public.preparation_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "Users update own preparation" on public.preparation_progress;
create policy "Users update own preparation"
on public.preparation_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users delete own preparation" on public.preparation_progress;
create policy "Users delete own preparation"
on public.preparation_progress for delete
using (auth.uid() = user_id);

create index if not exists preparation_progress_user_id_idx
on public.preparation_progress(user_id);
